(function(){
  var form=document.getElementById('requestForm');
  var steps=document.querySelectorAll('.wizard-step');
  var progressBar=document.getElementById('progressBar');
  var stepLabel=document.getElementById('stepLabel');
  var roomsEl=document.getElementById('rooms');
  var packageOptions=document.getElementById('packageOptions');
  var cartItems=document.getElementById('cartItems');
  var cartBreakdown=document.getElementById('cartBreakdown');
  var cartEstimate=document.getElementById('cartEstimate');
  var cartEstimateNote=document.getElementById('cartEstimateNote');
  var finalEstimate=document.getElementById('finalEstimate');
  var finalNote=document.getElementById('finalNote');
  var finalIncluded=document.getElementById('finalIncluded');
  var includedPreview=document.getElementById('includedPreview');
  var photoInput=document.getElementById('photos');
  var photoList=document.getElementById('photoList');
  var status=document.getElementById('formStatus');
  var current=1;

  function money(n){return new Intl.NumberFormat('nb-NO',{style:'currency',currency:'NOK',maximumFractionDigits:0}).format(Math.round(n/100)*100)}
  function has(arr,val){return arr.indexOf(val)!==-1}
  function services(){var out=[],nodes=document.querySelectorAll('input[name="service"]:checked');for(var i=0;i<nodes.length;i++)out.push(nodes[i].value);return out}
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function conditionValue(){var el=document.querySelector('input[name="condition"]:checked');return el?el.value:'ready'}
  function roomTemplate(first){return '<article class="room-card simple-room"><div class="room-title"><strong>Rom <span class="room-number"></span></strong>'+(first?'':'<button type="button" class="remove-room">Fjern</button>')+'</div><div class="field-grid"><label>Type rom<select class="r-type"><option value="">Velg romtype</option><option>Stue</option><option>Soverom</option><option>Gang</option><option>Kjøkken</option><option>Kontor</option><option>Annet</option></select></label><label>Ca. størrelse<input class="r-area" type="number" min="1" placeholder="f.eks. 20 m²"></label></div></article>'}
  function renumber(){var cards=roomsEl.querySelectorAll('.room-card');for(var i=0;i<cards.length;i++)cards[i].querySelector('.room-number').textContent=i+1}
  function bindRooms(){var fields=roomsEl.querySelectorAll('input,select');for(var i=0;i<fields.length;i++){fields[i].oninput=updateAll;fields[i].onchange=updateAll}var remove=roomsEl.querySelectorAll('.remove-room');for(var j=0;j<remove.length;j++)remove[j].onclick=function(){this.parentNode.parentNode.remove();renumber();updateAll()}}
  function addRoom(first){roomsEl.insertAdjacentHTML('beforeend',roomTemplate(first));renumber();bindRooms();updateAll()}
  function getRooms(){var cards=roomsEl.querySelectorAll('.room-card'),out=[];for(var i=0;i<cards.length;i++)out.push({type:cards[i].querySelector('.r-type').value||('Rom '+(i+1)),area:Math.max(0,Number(cards[i].querySelector('.r-area').value)||0)});return out}
  function totalArea(){var rs=getRooms(),sum=0;for(var i=0;i<rs.length;i++)sum+=rs[i].area;return sum}
  function optionChecked(name){var el=document.querySelector('input[name="'+name+'"]');return !!(el&&el.checked)}

  function buildPackageOptions(){var s=services(),html='';if(has(s,'Gulv'))html+='<div class="package-card"><div class="package-title"><div><strong>Vil du ha hjelp med noe rundt gulvleggingen?</strong><small>Selve gulvleggingen er allerede med i estimatet. Kryss bare av for det ekstra du ønsker hjelp med.</small></div><span>Valgfritt</span></div><label class="package-row"><input type="checkbox" name="opt_demo_floor"><span><b>Fjerne gammelt gulv</b><small>Lar du gulvet være ferdig revet før jeg kommer, betaler du ikke for rivearbeid.</small></span></label><label class="package-row"><input type="checkbox" name="opt_dispose"><span><b>Kjøre bort gammelt gulv og avfall</b><small>Kjører du bort avfallet selv, sparer du kostnaden for bortkjøring.</small></span></label><label class="package-row"><input type="checkbox" name="opt_pickup"><span><b>Hente det nye gulvet</b><small>Har du gulvet klart hjemme, slipper du kostnaden for henting.</small></span></label><label class="package-row"><input type="checkbox" name="opt_skirting"><span><b>Montere nye gulvlister</b><small>Velg hvis du ønsker rommet ferdig listet etter gulvleggingen.</small></span></label><label class="package-row"><input type="checkbox" name="opt_furniture"><span><b>Hjelp til å flytte møbler</b><small>Tømmer du rommet selv før oppstart, kommer det ingen kostnad for møbelflytting.</small></span></label></div>';if(has(s,'Vegger og gips')||has(s,'Panel')||has(s,'Komplett rom'))html+='<div class="package-card"><div class="package-title"><div><strong>Vil du ha hjelp før arbeidet starter?</strong><small>Kryss bare av hvis du ønsker at Moholdt skal gjøre dette også.</small></div><span>Valgfritt</span></div><label class="package-row"><input type="checkbox" name="opt_demo_wall"><span><b>Rive eksisterende vegg/panel</b><small>River du selv på forhånd, betaler du ikke for rivearbeidet.</small></span></label><label class="package-row"><input type="checkbox" name="opt_dispose_other"><span><b>Kjøre bort riveavfall</b><small>Kjører du bort avfallet selv, sparer du kostnaden for bortkjøring.</small></span></label></div>';packageOptions.innerHTML=html||'<div class="optional-block"><strong>Ingen ekstra valg nødvendig.</strong><p>Du kan gå rett videre.</p></div>';var inputs=packageOptions.querySelectorAll('input');for(var i=0;i<inputs.length;i++)inputs[i].onchange=updateAll}
  function baseCalc(){var area=totalArea(),s=services(),labor=0,lines=[],included=[];if(!area||!s.length)return {labor:0,lines:[],included:[]};for(var i=0;i<s.length;i++){var service=s[i],amount=0,label=service;if(service==='Gulv'){amount=Math.max(5500,320*area);label='Legging av nytt gulv';included.push('Legging og tilpasning av nytt gulv','Kapping rundt hjørner, dører og avslutninger','Normal opprydding etter arbeidet')}if(service==='Vegger og gips'){amount=520*area;included.push('Gipsing og normalt veggarbeid','Tilpasning og montering','Normal opprydding')}if(service==='Panel'){amount=390*area;included.push('Montering og tilpasning av panel','Normal opprydding')}if(service==='Lister og foringer'){amount=110*area;included.push('Montering og tilpasning av lister/foringer')}if(service==='Komplett rom'){amount=850*area;included.push('Arbeid med flere overflater i rommet','Tilpasning og montering','Normal opprydding')}if(amount){labor+=amount;lines.push([label,amount])}}if(has(s,'Gulv')){if(optionChecked('opt_demo_floor')){var d=1200+area*35;labor+=d;lines.push(['Fjerne gammelt gulv',d]);included.push('Fjerning av gammelt gulv')}if(optionChecked('opt_dispose')){var x=900+area*20;labor+=x;lines.push(['Bortkjøring',x]);included.push('Bortkjøring av gammelt gulv/avfall')}if(optionChecked('opt_pickup')){labor+=1000;lines.push(['Henting av gulv',1000]);included.push('Henting av nytt gulv/materialer')}if(optionChecked('opt_skirting')){var sk=1500+area*35;labor+=sk;lines.push(['Montering av gulvlister',sk]);included.push('Montering av nye gulvlister')}if(optionChecked('opt_furniture')){var f=900+area*15;labor+=f;lines.push(['Flytting av møbler',f]);included.push('Flytting av møbler før arbeidet')}}if(optionChecked('opt_demo_wall')){var w=1500+area*55;labor+=w;lines.push(['Rivearbeid vegg/panel',w]);included.push('Riving av eksisterende vegg/panel')}if(optionChecked('opt_dispose_other')){var b=1000+area*25;labor+=b;lines.push(['Bortkjøring riveavfall',b]);included.push('Bortkjøring av riveavfall')}return {labor:labor,lines:lines,included:included}}
  function conditionNote(){var c=conditionValue();if(c==='lay_as_is')return 'Estimatet gjelder legging på eksisterende underlag uten avretting. Endelig faglig vurdering gjøres før oppstart.';if(c==='check')return 'Estimatet gjelder gulvlegging. Moholdt kontrollerer underlaget før oppstart. Eventuell avretting avtales og prises separat.';if(c==='level')return 'Avretting er ikke inkludert. Omfang og pris må vurderes separat før endelig pris.';return 'Dette er et foreløpig estimat. Endelig pris avtales før oppstart.'}
  function estimate(){var c=baseCalc();return {labor:c.labor,low:c.labor*.95,high:c.labor*1.10,lines:c.lines,included:c.included}}
  function updateAll(){var e=estimate(),rs=getRooms(),html='';for(var i=0;i<rs.length;i++)html+='<div class="cart-item"><span><strong>'+esc(rs[i].type)+'</strong>'+(rs[i].area?' • '+rs[i].area+' m²':'')+'</span></div>';cartItems.innerHTML=html||'<p class="empty-cart">Legg inn et rom.</p>';var breakdown='';for(var j=0;j<e.lines.length;j++)breakdown+='<span><em>'+esc(e.lines[j][0])+'</em><strong>'+money(e.lines[j][1])+'</strong></span>';cartBreakdown.innerHTML=breakdown;if(e.labor){var text=money(e.low)+' – '+money(e.high);cartEstimate.textContent=text;finalEstimate.textContent=text;cartEstimateNote.textContent=conditionNote();finalNote.textContent=conditionNote()}else{cartEstimate.textContent='–';finalEstimate.textContent='–';cartEstimateNote.textContent='Velg jobb og legg inn ca. størrelse.';finalNote.textContent='Endelig pris avtales før oppstart.'}var inc='';for(var k=0;k<e.included.length;k++)inc+='<li>✓ '+esc(e.included[k])+'</li>';includedPreview.innerHTML=inc?'<strong>Inkludert i estimatet</strong><ul>'+inc+'</ul>:'';finalIncluded.innerHTML=inc?'<h4>Dette er inkludert</h4><ul>'+inc+'</ul>:''}
  function showStep(n){current=n;if(n===3)buildPackageOptions();for(var i=0;i<steps.length;i++)steps[i].classList.toggle('active',Number(steps[i].getAttribute('data-step'))===n);if(n<=4){progressBar.style.width=(n*25)+'%';stepLabel.textContent='Steg '+n+' av 4';stepLabel.style.display='block'}else{progressBar.style.width='100%';stepLabel.style.display='none'}updateAll();window.location.hash='foresporsel'}
  function validate(){status.textContent='';if(current===1&&!services().length){alert('Velg minst én type arbeid.');return false}if(current===2){var rs=getRooms(),ok=false;for(var i=0;i<rs.length;i++)if(rs[i].area)ok=true;if(!ok){alert('Legg inn ca. størrelse på minst ett rom.');return false}}if(current===4&&!document.getElementById('name').value.trim()){status.textContent='Fyll inn navn.';return false}if(current===4&&!document.getElementById('phone').value.trim()){status.textContent='Fyll inn telefonnummer.';return false}return true}
  var next=document.querySelectorAll('.next');for(var i=0;i<next.length;i++)next[i].onclick=function(){if(validate())showStep(Math.min(current+1,4))};var prev=document.querySelectorAll('.prev');for(var j=0;j<prev.length;j++)prev[j].onclick=function(){showStep(Math.max(current-1,1))};document.getElementById('cartBack').onclick=function(){showStep(Math.max(current-1,1))};document.getElementById('addRoom').onclick=function(){addRoom(false)};var globalChecks=document.querySelectorAll('input[name="service"]');for(var g=0;g<globalChecks.length;g++)globalChecks[g].onchange=updateAll;var materialStatus=document.getElementById('materialStatus');var materialFields=document.getElementById('materialFields');materialStatus.onchange=function(){materialFields.classList.toggle('hidden',materialStatus.value==='none')};var conditionNodes=document.querySelectorAll('input[name="condition"]');for(var c=0;c<conditionNodes.length;c++)conditionNodes[c].onchange=updateAll;photoInput.onchange=function(){photoList.innerHTML=photoInput.files.length?'<strong>'+photoInput.files.length+' bilder valgt</strong>':'<span>Ingen bilder valgt.</span>'};
  form.onsubmit=function(ev){ev.preventDefault();if(!validate())return;var p=estimate(),cv=conditionValue();var inquiry={id:Date.now(),customer:document.getElementById('name').value.trim(),phone:document.getElementById('phone').value.trim(),rooms:getRooms(),services:services(),timing:document.getElementById('timing').value,options:{demoFloor:optionChecked('opt_demo_floor'),dispose:optionChecked('opt_dispose'),pickup:optionChecked('opt_pickup'),skirting:optionChecked('opt_skirting'),furniture:optionChecked('opt_furniture'),demoWall:optionChecked('opt_demo_wall'),disposeOther:optionChecked('opt_dispose_other')},material:{status:materialStatus.value,name:document.getElementById('materialName').value.trim(),link:document.getElementById('materialLink').value.trim()},condition:cv,description:document.getElementById('description').value.trim(),photos:[],estimate:p.labor?money(p.low)+' – '+money(p.high):'Må vurderes',needsReview:cv!=='ready',status:'new',createdAt:new Date().toISOString()};for(var i=0;i<photoInput.files.length;i++)inquiry.photos.push(photoInput.files[i].name);var q=JSON.parse(localStorage.getItem('moholdtInquiries')||'[]');q.unshift(inquiry);localStorage.setItem('moholdtInquiries',JSON.stringify(q));showStep(5)};
  addRoom(true);showStep(1);
})();